### ISSUE TITLE
Segwit is patented by blockstream and must be removed

### ISSUE THREAD

**Issue by epowermining** [bcoin-org/bcoin-extension-blocks#3]
https://falkvinge.net/2017/05/01/blockstream-patents-segwit-makes-pieces-fall-place/

**Comment by painlord2k** [comment]
I would suggest to formally ask Blockstream and Core developers to declare:

1) Do you know any patent applying or could apply to any SegWit technology or Lighting Network Technology?
2) Do you own any patent applying to SegWit or Lignting Network?
3) Do you know any patent applying to SegWit or LN owned by some other person or entity?
4) Any other questions a good IP lawyer would come up.

**Comment by chjj** [comment]
As of right now, the only public patents I see are for sidechains and confidential transactions:

- https://www.google.com/?tbm=pts#tbm=pts&q=ininventor:%22Gregory+Maxwell%22
- https://www.google.com/?tbm=pts#tbm=pts&q=inassignee:%22Blockstream+Corporation%22

I don't expect that to change, but we can reopen this and discuss it if it does change in the near future.

> Do you know any patent applying or could apply to any SegWit technology or Lighting Network Technology?

Blockstream can't patent Lightning. They're not the inventors of it. The only ones with patent rights would be [Tadge Dryja and Joseph Poon][ln], and I'm pretty certain that they haven't filed a patent for it.

Closing.

[ln]: https://lightning.network/lightning-network-paper.pdf
